Repository leapfrogtechnology/async-store, pull requests merged in 2019-07, with the labels that each got.

#6 Refactor domain implementation and add find() function
  src/AsyncStore.ts
  src/AsyncStoreParams.ts
  src/impl/domain.ts
  src/index.ts
  test/domain.test.ts
Labels: enhancement

#7 Cleanup and update dependencies
  package.json
  yarn.lock
Labels: enhancement

#8 Update docs in README.md
  README.md
Labels: documentation

#9 Add a sample project using Express and TypeScript
  README.md
  examples/express-ts/.gitignore
  examples/express-ts/README.md
  examples/express-ts/backpack.config.js
  examples/express-ts/package.json
  examples/express-ts/src/index.ts
  examples/express-ts/src/middlewares.ts
  examples/express-ts/src/service.ts
  examples/express-ts/tsconfig.json
  examples/express-ts/tslint.json
  examples/express-ts/yarn.lock
Labels: example

#10 Add GitHub URL and update description in package.json
  README.md
  package.json
Labels: documentation

#12 Minor improvements on the documentation
  README.md
Labels: documentation

#18 Add test cases for getId() method
  README.md
  test/domain.test.ts
Labels: test

#19 Add isInitialized() doc
  README.md
Labels: documentation
