Repository leapfrogtechnology/async-store, pull requests merged in 2019-10, with the labels that each got.

#32 Add new accessor function getAll()
  README.md
  src/AsyncStore.ts
  src/impl/domain.ts
  src/index.ts
  test/domain.test.ts
Labels: feature

#33 Add missing tests for edge cases
  test/domain.test.ts
  test/general.test.ts
Labels: test

#34 Remove unreachable code
  src/impl/domain.ts
Labels: improvement

#35 Add implementation to get short id
  README.md
  src/AsyncStore.ts
  src/impl/domain.ts
  src/index.ts
  test/domain.test.ts
Labels: feature

#36 Add example project for koa
  README.md
  examples/koa-http-server-js/.babelrc
  examples/koa-http-server-js/.eslintrc
  examples/koa-http-server-js/.gitignore
  examples/koa-http-server-js/README.md
  examples/koa-http-server-js/backpack.config.js
  examples/koa-http-server-js/eslint.json
  examples/koa-http-server-js/package.json
  examples/koa-http-server-js/src/index.js
  examples/koa-http-server-js/src/logger.js
  examples/koa-http-server-js/src/middlewares.js
  examples/koa-http-server-js/src/service.js
  examples/koa-http-server-js/yarn.lock
Labels: documentation, example
